stages:
  - build
  - upload
  - release

workflow:
  rules:
    - if: $CI_COMMIT_TAG

build:
  stage: build
  tags:
    - windows
  script:
    - ./build/compiler/ahk2exe.exe /in "ACCreplay.ahk" /out "./build/ACCreplay.exe" /icon "./build/icon/icon.ico" /base "./build/compiler/Unicode 32-bit.bin"
  artifacts:
    paths:
      - ./build/ACCreplay.exe
    expire_in: 1 day

upload:
  stage: upload
  script:
    - Invoke-RestMethod -Headers @{ "JOB-TOKEN"="$CI_JOB_TOKEN" } -InFile ./build/ACCreplay.exe -uri "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/ACCreplay.exe" -Method put

release:
  stage: release
  tags:
    - gitlab-org-docker
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo "running release_job"
  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: "$CI_COMMIT_TAG"
    name: "Release $CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG"
    assets:
      links:
        - name: "ACCreplay.exe"
          url: "https://example.com"
